### ISSUE TITLE
Question for work logic

### ISSUE THREAD

**Issue by goodboychan** [intel/yoko-tool#4]
Hi, 
I`m considering to use this tool for gathering power measurement.
Just wondering that, on the official manual, most of yokogawa measuring program requires specific dll file called [TMCTL.dll](https://tmi.yokogawa.com/eu/library/documents-downloads/software/tmctl/).
So, is yoko-tool abstract version of TMCTL.dll?

Thanks in advance.

**Comment by dedekind** [comment]
This tool was created because there was no tool available for Linux. Yoko-tool is a Linux tool. DLL is a Windows technology, as far as I know. Yoko-tool does not use TMCTL.dll.

**Comment by goodboychan** [comment]
right, That's why I'm looking for. Thanks for explanation.
